return {
  {
    "nvim-treesitter/nvim-treesitter",
    version = "0.9.3",  -- the last supported version
    build = ":TSUpdate",
    opts = {
      -- indent = { enable = true },
      highlight = { enable = true },
      -- folds = { enable = true },
      ensure_installed = {
        "bash",
        "c",
        "diff",
        "dockerfile",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "go",
        "gomod",
        "gosum",
        "gowork",
        "helm",
        "html",
        "javascript",
        "jsdoc",
        "json",
        "jsonnet",
        -- "kcl",
        "lua",
        "luadoc",
        "luap",
        "markdown",
        "markdown_inline",
        "norg",
        "printf",
        "python",
        "query",
        "regex",
        "sql",
        "starlark",
        "terraform",
        "toml",
        "tsx",
        "typescript",
        "vim",
        "vimdoc",
        "xml",
        "yaml",
      },
    },
    config = function(_, opts)
      require("nvim-treesitter.configs").setup(opts)
    end,
  },

  {
    "nvim-treesitter/nvim-treesitter-context",
    -- event = "LazyFile",
    opts = function()
      return { mode = "cursor", max_lines = 3 }
    end,
  },
}
