cask_args appdir: '/Applications'

tap "goreleaser/tap", trusted: true
tap "caarlos0/tap", trusted: true
tap "johanhaleby/kubetail", trusted: true
tap "go-swagger/go-swagger", trusted: true

# Custom taps
tap "datawire/blackbird", trusted: true
tap "derailed/k9s", trusted: true
tap "universal-ctags/universal-ctags", trusted: true
tap "versent/homebrew-taps", trusted: true
tap "weaveworks/tap", trusted: true
tap "noahgorstein/tap", trusted: true
tap "mdsakalu/tap", trusted: true # macnetmon

# App essentials
# cask "alacritty"
# cask "github"
cask "gpg-suite"
# cask "ngrok"
# cask "transmission"

# Homebrew essentials
brew "ack"
brew "aws-iam-authenticator"
brew "awscli"
brew "axel"
brew "bat"
brew "cmake"
brew "diff-so-fancy"
brew "direnv"
brew "dnsmasq"
brew "fzf"
brew "git"
brew "glab"
# brew "gnupg"
brew "golang"
brew "goreleaser"
brew "go-swagger"
brew "graphviz"
brew "helm"
brew "highlight"
brew "htop"
brew "httpie"
brew "hub" # Run the following to have vim-fugitive work with GitHub: echo 'machine api.github.com login <user> password <token>' >> ~/.netrc
brew "jsonnet"
brew "jq"
brew "jqp" # tui playground for jq
brew "k9s"
brew "kubectx"
brew "kubernetes-cli"
brew "kubetail"
brew "kustomize"
brew "lazydocker"
brew "lazygit"
brew "macnetmon"
brew "markdown"
brew "mas"
brew "minikube"
brew "ncurses"
brew "neovim"
brew "nvm"
brew "pgcli" # postgres cli
brew "protobuf"
brew "python"
brew "python3"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "rust"
brew "saml2aws"
brew "starship"
brew "stern"
brew "stow"
brew "svu"
brew "tfenv"
brew "tig"
brew "tmuxinator"
# brew "tmuxinator-fzf-start"
brew "tmux"
brew "tree"
brew "tree"
brew "universal-ctags"
# brew "ctags"
brew "wget"
brew "yq"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
